config/routes.rb
Circles::Application.routes.draw do

  root :to => "nodes#index"

  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :touches

  resources :shapes

  resources :links

  resources :relations

  resources :characters

  resources :seeds

  resources :nodes

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/character.rb
class Character < ActiveRecord::Base
  belongs_to :seed
  belongs_to :touch
  attr_accessible :default, :deleted_at, :length, :name, :sort_no
end

app/models/link.rb
class Link < ActiveRecord::Base
  belongs_to :node
  attr_accessible :linked_id, :type
end

app/models/node.rb
class Node < ActiveRecord::Base
  belongs_to :seed
  attr_accessible :deleted_at, :name
end

app/models/relation.rb
class Relation < ActiveRecord::Base
  belongs_to :seed
  attr_accessible :related_id, :type
end

app/models/seed.rb
class Seed < ActiveRecord::Base
  attr_accessible :deleted_at, :name, :sort_no
end

app/models/shape.rb
class Shape < ActiveRecord::Base
  belongs_to :node
  belongs_to :character
  attr_accessible :display, :value
end

app/models/touch.rb
class Touch < ActiveRecord::Base
  attr_accessible :decimal_place, :html, :name, :source_sql
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/links_controller.rb
class LinksController < InheritedResources::Base
end

app/controllers/nodes_controller.rb
class NodesController < InheritedResources::Base
  before_filter :authenticate_user!
end

app/controllers/relations_controller.rb
class RelationsController < InheritedResources::Base
end

app/controllers/seeds_controller.rb
class SeedsController < InheritedResources::Base
end

app/controllers/shapes_controller.rb
class ShapesController < InheritedResources::Base
end

app/controllers/touches_controller.rb
class TouchesController < InheritedResources::Base
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/nodes_helper.rb
module NodesHelper
end

app/helpers/relations_helper.rb
module RelationsHelper
end

app/helpers/seeds_helper.rb
module SeedsHelper
end

app/helpers/shapes_helper.rb
module ShapesHelper
end

app/helpers/touches_helper.rb
module TouchesHelper
end

app/views/links/_form.html.erb
<%= form_for(@link) do |f| %>
  <% if @link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% @link.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :node %><br />
    <%= f.text_field :node %>
  </div>
  <div class="field">
    <%= f.label :linked_id %><br />
    <%= f.number_field :linked_id %>
  </div>
  <div class="field">
    <%= f.label :type %><br />
    <%= f.text_field :type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/links/edit.html.erb
<h1>Editing link</h1>

<%= render 'form' %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/links/index.html.erb
<h1>Listing links</h1>

<table>
  <tr>
    <th>Node</th>
    <th>Linked</th>
    <th>Type</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @links.each do |link| %>
  <tr>
    <td><%= link.node %></td>
    <td><%= link.linked_id %></td>
    <td><%= link.type %></td>
    <td><%= link_to 'Show', link %></td>
    <td><%= link_to 'Edit', edit_link_path(link) %></td>
    <td><%= link_to 'Destroy', link, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Link', new_link_path %>

app/views/links/new.html.erb
<h1>New link</h1>

<%= render 'form' %>

<%= link_to 'Back', links_path %>

app/views/links/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Node:</b>
  <%= @link.node %>
</p>

<p>
  <b>Linked:</b>
  <%= @link.linked_id %>
</p>

<p>
  <b>Type:</b>
  <%= @link.type %>
</p>


<%= link_to 'Edit', edit_link_path(@link) %> |
<%= link_to 'Back', links_path %>

app/views/nodes/_form.html.erb
<%= form_for(@node) do |f| %>
  <% if @node.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@node.errors.count, "error") %> prohibited this node from being saved:</h2>

      <ul>
      <% @node.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :seed %><br />
    <%= f.text_field :seed %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :deleted_at %><br />
    <%= f.datetime_select :deleted_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/nodes/edit.html.erb
<h1>Editing node</h1>

<%= render 'form' %>

<%= link_to 'Show', @node %> |
<%= link_to 'Back', nodes_path %>

app/views/nodes/index.html.erb
<h1>Listing nodes</h1>

<table>
  <tr>
    <th>Seed</th>
    <th>Name</th>
    <th>Deleted at</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @nodes.each do |node| %>
  <tr>
    <td><%= node.seed %></td>
    <td><%= node.name %></td>
    <td><%= node.deleted_at %></td>
    <td><%= link_to 'Show', node %></td>
    <td><%= link_to 'Edit', edit_node_path(node) %></td>
    <td><%= link_to 'Destroy', node, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Node', new_node_path %>

app/views/nodes/new.html.erb
<h1>New node</h1>

<%= render 'form' %>

<%= link_to 'Back', nodes_path %>

app/views/nodes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Seed:</b>
  <%= @node.seed %>
</p>

<p>
  <b>Name:</b>
  <%= @node.name %>
</p>

<p>
  <b>Deleted at:</b>
  <%= @node.deleted_at %>
</p>


<%= link_to 'Edit', edit_node_path(@node) %> |
<%= link_to 'Back', nodes_path %>

app/views/relations/_form.html.erb
<%= form_for(@relation) do |f| %>
  <% if @relation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@relation.errors.count, "error") %> prohibited this relation from being saved:</h2>

      <ul>
      <% @relation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :seed %><br />
    <%= f.text_field :seed %>
  </div>
  <div class="field">
    <%= f.label :related_id %><br />
    <%= f.number_field :related_id %>
  </div>
  <div class="field">
    <%= f.label :type %><br />
    <%= f.text_field :type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/relations/edit.html.erb
<h1>Editing relation</h1>

<%= render 'form' %>

<%= link_to 'Show', @relation %> |
<%= link_to 'Back', relations_path %>

app/views/relations/index.html.erb
<h1>Listing relations</h1>

<table>
  <tr>
    <th>Seed</th>
    <th>Related</th>
    <th>Type</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @relations.each do |relation| %>
  <tr>
    <td><%= relation.seed %></td>
    <td><%= relation.related_id %></td>
    <td><%= relation.type %></td>
    <td><%= link_to 'Show', relation %></td>
    <td><%= link_to 'Edit', edit_relation_path(relation) %></td>
    <td><%= link_to 'Destroy', relation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Relation', new_relation_path %>

app/views/relations/new.html.erb
<h1>New relation</h1>

<%= render 'form' %>

<%= link_to 'Back', relations_path %>

app/views/relations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Seed:</b>
  <%= @relation.seed %>
</p>

<p>
  <b>Related:</b>
  <%= @relation.related_id %>
</p>

<p>
  <b>Type:</b>
  <%= @relation.type %>
</p>


<%= link_to 'Edit', edit_relation_path(@relation) %> |
<%= link_to 'Back', relations_path %>

app/views/seeds/_form.html.erb
<%= form_for(@seed) do |f| %>
  <% if @seed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@seed.errors.count, "error") %> prohibited this seed from being saved:</h2>

      <ul>
      <% @seed.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :sort_no %><br />
    <%= f.number_field :sort_no %>
  </div>
  <div class="field">
    <%= f.label :deleted_at %><br />
    <%= f.datetime_select :deleted_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/seeds/edit.html.erb
<h1>Editing seed</h1>

<%= render 'form' %>

<%= link_to 'Show', @seed %> |
<%= link_to 'Back', seeds_path %>

app/views/seeds/index.html.erb
<h1>Listing seeds</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Sort no</th>
    <th>Deleted at</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @seeds.each do |seed| %>
  <tr>
    <td><%= seed.name %></td>
    <td><%= seed.sort_no %></td>
    <td><%= seed.deleted_at %></td>
    <td><%= link_to 'Show', seed %></td>
    <td><%= link_to 'Edit', edit_seed_path(seed) %></td>
    <td><%= link_to 'Destroy', seed, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Seed', new_seed_path %>

app/views/seeds/new.html.erb
<h1>New seed</h1>

<%= render 'form' %>

<%= link_to 'Back', seeds_path %>

app/views/seeds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @seed.name %>
</p>

<p>
  <b>Sort no:</b>
  <%= @seed.sort_no %>
</p>

<p>
  <b>Deleted at:</b>
  <%= @seed.deleted_at %>
</p>


<%= link_to 'Edit', edit_seed_path(@seed) %> |
<%= link_to 'Back', seeds_path %>

app/views/shapes/_form.html.erb
<%= form_for(@shape) do |f| %>
  <% if @shape.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shape.errors.count, "error") %> prohibited this shape from being saved:</h2>

      <ul>
      <% @shape.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :node %><br />
    <%= f.text_field :node %>
  </div>
  <div class="field">
    <%= f.label :character %><br />
    <%= f.text_field :character %>
  </div>
  <div class="field">
    <%= f.label :value %><br />
    <%= f.text_field :value %>
  </div>
  <div class="field">
    <%= f.label :display %><br />
    <%= f.text_field :display %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shapes/edit.html.erb
<h1>Editing shape</h1>

<%= render 'form' %>

<%= link_to 'Show', @shape %> |
<%= link_to 'Back', shapes_path %>

app/views/shapes/index.html.erb
<h1>Listing shapes</h1>

<table>
  <tr>
    <th>Node</th>
    <th>Character</th>
    <th>Value</th>
    <th>Display</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @shapes.each do |shape| %>
  <tr>
    <td><%= shape.node %></td>
    <td><%= shape.character %></td>
    <td><%= shape.value %></td>
    <td><%= shape.display %></td>
    <td><%= link_to 'Show', shape %></td>
    <td><%= link_to 'Edit', edit_shape_path(shape) %></td>
    <td><%= link_to 'Destroy', shape, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Shape', new_shape_path %>

app/views/shapes/new.html.erb
<h1>New shape</h1>

<%= render 'form' %>

<%= link_to 'Back', shapes_path %>

app/views/shapes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Node:</b>
  <%= @shape.node %>
</p>

<p>
  <b>Character:</b>
  <%= @shape.character %>
</p>

<p>
  <b>Value:</b>
  <%= @shape.value %>
</p>

<p>
  <b>Display:</b>
  <%= @shape.display %>
</p>


<%= link_to 'Edit', edit_shape_path(@shape) %> |
<%= link_to 'Back', shapes_path %>

app/views/touches/_form.html.erb
<%= form_for(@touch) do |f| %>
  <% if @touch.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@touch.errors.count, "error") %> prohibited this touch from being saved:</h2>

      <ul>
      <% @touch.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :decimal_place %><br />
    <%= f.number_field :decimal_place %>
  </div>
  <div class="field">
    <%= f.label :html %><br />
    <%= f.text_field :html %>
  </div>
  <div class="field">
    <%= f.label :source_sql %><br />
    <%= f.text_field :source_sql %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/touches/edit.html.erb
<h1>Editing touch</h1>

<%= render 'form' %>

<%= link_to 'Show', @touch %> |
<%= link_to 'Back', touches_path %>

app/views/touches/index.html.erb
<h1>Listing touches</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Decimal place</th>
    <th>Html</th>
    <th>Source sql</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @touches.each do |touch| %>
  <tr>
    <td><%= touch.name %></td>
    <td><%= touch.decimal_place %></td>
    <td><%= touch.html %></td>
    <td><%= touch.source_sql %></td>
    <td><%= link_to 'Show', touch %></td>
    <td><%= link_to 'Edit', edit_touch_path(touch) %></td>
    <td><%= link_to 'Destroy', touch, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Touch', new_touch_path %>

app/views/touches/new.html.erb
<h1>New touch</h1>

<%= render 'form' %>

<%= link_to 'Back', touches_path %>

app/views/touches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @touch.name %>
</p>

<p>
  <b>Decimal place:</b>
  <%= @touch.decimal_place %>
</p>

<p>
  <b>Html:</b>
  <%= @touch.html %>
</p>

<p>
  <b>Source sql:</b>
  <%= @touch.source_sql %>
</p>


<%= link_to 'Edit', edit_touch_path(@touch) %> |
<%= link_to 'Back', touches_path %>