config/routes.rb
Circles::Application.routes.draw do

  root :to => "nodes#index"

  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :touches

  resources :shapes

  resources :links

  resources :relations

  resources :characters

  resources :seeds

  resources :nodes

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/character.rb
class Character < ActiveRecord::Base
  belongs_to :seed
  belongs_to :touch
  attr_accessible :default, :deleted_at, :length, :name, :sort_no
end

app/models/link.rb
class Link < ActiveRecord::Base
  belongs_to :node
  attr_accessible :linked_id, :type
end

app/models/node.rb
class Node < ActiveRecord::Base
  belongs_to :seed
  attr_accessible :deleted_at, :name
end

app/models/relation.rb
class Relation < ActiveRecord::Base
  belongs_to :seed
  attr_accessible :related_id, :type
end

app/models/seed.rb
class Seed < ActiveRecord::Base
  attr_accessible :deleted_at, :name, :sort_no
end

app/models/shape.rb
class Shape < ActiveRecord::Base
  belongs_to :node
  belongs_to :character
  attr_accessible :display, :value
end

app/models/touch.rb
class Touch < ActiveRecord::Base
  attr_accessible :decimal_place, :html, :name, :source_sql
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/characters_controller.rb
class CharactersController < InheritedResources::Base
end

app/controllers/links_controller.rb
class LinksController < InheritedResources::Base
end

app/controllers/nodes_controller.rb
class NodesController < InheritedResources::Base
  before_filter :authenticate_user!
end

app/controllers/seeds_controller.rb
class SeedsController < InheritedResources::Base
end

app/controllers/shapes_controller.rb
class ShapesController < InheritedResources::Base
end

app/controllers/touches_controller.rb
class TouchesController < InheritedResources::Base
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/nodes_helper.rb
module NodesHelper
end

app/helpers/relations_helper.rb
module RelationsHelper
end

app/helpers/seeds_helper.rb
module SeedsHelper
end

app/helpers/shapes_helper.rb
module ShapesHelper
end

app/helpers/touches_helper.rb
module TouchesHelper
end

app/views/characters/_form.html.erb
<%= form_for(@character) do |f| %>
  <% if @character.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@character.errors.count, "error") %> prohibited this character from being saved:</h2>

      <ul>
      <% @character.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :seed %><br />
    <%= f.text_field :seed %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :touch %><br />
    <%= f.text_field :touch %>
  </div>
  <div class="field">
    <%= f.label :default %><br />
    <%= f.text_field :default %>
  </div>
  <div class="field">
    <%= f.label :length %><br />
    <%= f.number_field :length %>
  </div>
  <div class="field">
    <%= f.label :sort_no %><br />
    <%= f.number_field :sort_no %>
  </div>
  <div class="field">
    <%= f.label :deleted_at %><br />
    <%= f.datetime_select :deleted_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/characters/edit.html.erb
<h1>Editing character</h1>

<%= render 'form' %>

<%= link_to 'Show', @character %> |
<%= link_to 'Back', characters_path %>

app/views/characters/index.html.erb
<h1>Listing characters</h1>

<table>
  <tr>
    <th>Seed</th>
    <th>Name</th>
    <th>Touch</th>
    <th>Default</th>
    <th>Length</th>
    <th>Sort no</th>
    <th>Deleted at</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @characters.each do |character| %>
  <tr>
    <td><%= character.seed %></td>
    <td><%= character.name %></td>
    <td><%= character.touch %></td>
    <td><%= character.default %></td>
    <td><%= character.length %></td>
    <td><%= character.sort_no %></td>
    <td><%= character.deleted_at %></td>
    <td><%= link_to 'Show', character %></td>
    <td><%= link_to 'Edit', edit_character_path(character) %></td>
    <td><%= link_to 'Destroy', character, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Character', new_character_path %>

app/views/characters/new.html.erb
<h1>New character</h1>

<%= render 'form' %>

<%= link_to 'Back', characters_path %>

app/views/characters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Seed:</b>
  <%= @character.seed %>
</p>

<p>
  <b>Name:</b>
  <%= @character.name %>
</p>

<p>
  <b>Touch:</b>
  <%= @character.touch %>
</p>

<p>
  <b>Default:</b>
  <%= @character.default %>
</p>

<p>
  <b>Length:</b>
  <%= @character.length %>
</p>

<p>
  <b>Sort no:</b>
  <%= @character.sort_no %>
</p>

<p>
  <b>Deleted at:</b>
  <%= @character.deleted_at %>
</p>


<%= link_to 'Edit', edit_character_path(@character) %> |
<%= link_to 'Back', characters_path %>